apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "xrootd.org/v1alpha1",
          "kind": "Xrootd",
          "metadata": {
            "name": "example-xrootd"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: xrootd-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Xrootd is the Schema for the xrootds API
      kind: Xrootd
      name: xrootds.xrootd.org
      version: v1alpha1
  displayName: Xrootd Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: xrootd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: xrootd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: xrootd-operator
            spec:
              containers:
              - command:
                - xrootd-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: xrootd-operator
                image: xrootd/xrootd-operator:0.0.0-5ff7abb
                imagePullPolicy: IfNotPresent
                name: xrootd-operator
                resources: {}
              serviceAccountName: xrootd-operator
      - name: xrootd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: xrootd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: xrootd-operator
            spec:
              containers:
              - command:
                - xrootd-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: xrootd-operator
                image: REPLACE_IMAGE
                imagePullPolicy: IfNotPresent
                name: xrootd-operator
                resources: {}
              serviceAccountName: xrootd-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - xrootd-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - xrootd.org
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: xrootd-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  version: 0.0.1
