
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - catalog.xrootd.org
  resources:
  - xrootdversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xrootd.xrootd.org
  resources:
  - xrootdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xrootd.xrootd.org
  resources:
  - xrootdclusters/status
  verbs:
  - get
  - patch
  - update
