# permissions for end users to view xrootdversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xrootdversion-viewer-role
rules:
- apiGroups:
  - catalog.xrootd.org
  resources:
  - xrootdversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.xrootd.org
  resources:
  - xrootdversions/status
  verbs:
  - get
