# permissions for end users to edit xrootdclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xrootdcluster-editor-role
rules:
- apiGroups:
  - xrootd.xrootd.org
  resources:
  - xrootdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xrootd.xrootd.org
  resources:
  - xrootdclusters/status
  verbs:
  - get
