apiVersion: xrootd.org/v1alpha1
kind: Xrootd
metadata:
  name: example-xrootd
spec:
  version: "latest-xrootdversion"
  redirector:
    replicas: 1
  worker:
    replicas: 2
    storage:
      capacity: "1Gi"
