apiVersion: xrootd.org/v1alpha1
kind: Xrootd
metadata:
  name: example-xrootd
spec:
  redirector:
    image: "qserv/xrootd:latest"
  worker:
    image: "qserv/xrootd:latest"
    storage:
      capacity: "1Gi"
