apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xrootds.xrootd.org
spec:
  group: xrootd.org
  names:
    kind: Xrootd
    listKind: XrootdList
    plural: xrootds
    singular: xrootd
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Xrootd is the Schema for the xrootds API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: XrootdSpec defines the desired state of Xrootd
            properties:
              config:
                description: XrootdConfigSpec defines the config spec used to generate
                  xrootd.cf
                type: object
              redirector:
                description: XrootdRedirectorSpec defines the desired state of Xrootd
                  redirectors
                properties:
                  image:
                    description: Image must have a tag
                    pattern: .+:.+
                    type: string
                  replicas:
                    format: int32
                    minimum: 1
                    type: integer
                type: object
              worker:
                description: XrootdWorkerSpec defines the desired state of Xrootd
                  workers
                properties:
                  image:
                    description: Image must have a tag
                    pattern: .+:.+
                    type: string
                  replicas:
                    format: int32
                    minimum: 1
                    type: integer
                  storage:
                    description: XrootdStorageSpec defines the storage spec of Xrootd
                      workers
                    properties:
                      capacity:
                        description: Capacity must be a storage capacity and should
                          be a valid quantity (ex, 1Gi)
                        type: string
                      class:
                        description: Class must be a storage class
                        type: string
                    type: object
                type: object
            type: object
          status:
            description: XrootdStatus defines the observed state of Xrootd
            properties:
              currentVersion:
                description: CurrentVersion is the current xrootd version
                type: string
              phase:
                description: Phase is the cluster running phase
                type: string
              reason:
                type: string
              redirectorStatus:
                description: MemberStatus defines the observed status of Xrootd member
                  (worker/redirector)
                properties:
                  ready:
                    description: Ready are the xrootd members that are ready to serve
                      requests The member names are the same as the xrootd pod names
                    items:
                      type: string
                    type: array
                  size:
                    description: Size is the current size of the cluster
                    type: integer
                  unready:
                    description: Unready are the xrootd members not ready to serve
                      requests
                    items:
                      type: string
                    type: array
                required:
                - size
                type: object
              workerStatus:
                description: MemberStatus defines the observed status of Xrootd member
                  (worker/redirector)
                properties:
                  ready:
                    description: Ready are the xrootd members that are ready to serve
                      requests The member names are the same as the xrootd pod names
                    items:
                      type: string
                    type: array
                  size:
                    description: Size is the current size of the cluster
                    type: integer
                  unready:
                    description: Unready are the xrootd members not ready to serve
                      requests
                    items:
                      type: string
                    type: array
                required:
                - size
                type: object
            required:
            - currentVersion
            - phase
            - redirectorStatus
            - workerStatus
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
