apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xrootds.xrootd.org
spec:
  group: xrootd.org
  names:
    kind: Xrootd
    listKind: XrootdList
    plural: xrootds
    singular: xrootd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Xrootd is the Schema for the xrootds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: XrootdSpec defines the desired state of Xrootd
          properties:
            config:
              description: XrootdConfigSpec defines the config spec used to generate
                xrootd.cf
              type: object
            redirector:
              description: XrootdRedirectorSpec defines the desired state of Xrootd
                redirectors
              properties:
                image:
                  description: Image must have a tag
                  pattern: .+:.+
                  type: string
                replicas:
                  format: int32
                  minimum: 1
                  type: integer
              type: object
            storage:
              description: XrootdStorageSpec defines the storage spec of Xrootd workers
              properties:
                storageCapacity:
                  type: string
                storageClass:
                  type: string
              type: object
            worker:
              description: XrootdWorkerSpec defines the desired state of Xrootd workers
              properties:
                image:
                  description: Image must have a tag
                  pattern: .+:.+
                  type: string
                replicas:
                  format: int32
                  minimum: 1
                  type: integer
              type: object
          type: object
        status:
          description: XrootdStatus defines the observed state of Xrootd
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
