apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: xrootd-operator.vX.Y.Z
spec:
  customresourcedefinitions:
    owned:
      - name: xrootdclusters.xrootd.xrootd.org
        specDescriptors:
          - description: Xrootd Version must refer to XrootdVersion CR which defines the xrootd protocol image to use in the cluster pods. The requested CR must be installed in the cluster's target namespace.
            displayName: Xrootd Version Name
            path: version
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes:catalog.xrootd.org:v1alpha1:XrootdVersion"
          - description: The desired number of worker pods for the xrootd cluster
            displayName: Worker Replicas
            path: worker.replicas
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podCount"
          - description: The desired number of redirector pods for the xrootd cluster
            displayName: Redirector Replicas
            path: redirector.replicas
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podCount"
          - description: The desired storage class to use for Dynamic Persistent Volume Provisioning for Worker pods
            displayName: Storage Class
            path: worker.storage.class
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes:storage.k8s.io:v1beta1:StorageClass"
        statusDescriptors:
          - description: The current version of the xrootd cluster.
            displayName: Current Version
            path: currentXrootdProtocol.version
          - description: The current xrootd image used by pods in the xrootd cluster.
            displayName: Current Xrootd Image
            path: currentXrootdProtocol.image
          - description: The current phase of the xrootd cluster.
            displayName: Phase
            path: phase
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes.phase"
          - description: Explanation for the current status of the cluster.
            displayName: Status Details
            path: reason
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes.phase:reason"
          - description: Number of redirector pods
            displayName: Redirectors count
            path: redirectorStatus.size
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podCount"
          - description: Current status of redirector pods
            displayName: Redirectors Status
            path: redirectorStatus.pods
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podStatuses"
          - description: Number of worker pods
            displayName: Workers count
            path: workerStatus.size
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podCount"
          - description: Current status of worker pods
            displayName: Workers Status
            path: workerStatus.pods
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podStatuses"
