# Xrootd operator CI workflow
---
name: "Xrootd operator CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy operator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Declare Version Variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=version::$(make version-image)"
      - name: Setup Operator SDK
        uses: shivanshs9/setup-k8s-operator-sdk@v1
        with:
          version: "^0.18.0"
      - name: Setup KinD
        uses: engineerd/setup-kind@v0.4.0
      - name: Build operator and Load Image
        run: make build
      - name: Deploy operator
        run: make deploy
      - name: Run Unit Tests
        run: make test
      - name: Apply a sample manifest
        run: |
          make kustomize
          kustomize build manifests/base | kubectl apply -f -
      - name: Run E2E Tests
        run: make VERBOSE=true test-e2e
