# Xrootd operator CI workflow
---
name: "Xrootd operator CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy operator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Declare Version Variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=version::$(make version)"
      - name: Setup Operator SDK
        uses: shivanshs9/setup-k8s-operator-sdk@v1
        with:
          version: "^0.17.0"
      - name: Setup KinD
        uses: engineerd/setup-kind@v0.4.0
      - name: Build operator
        run: make build
      - name: Load operator image
        run: kind load docker-image xrootd/xrootd-operator:${{ steps.vars.outputs.version }}
      - name: Deploy operator
        run: make deploy-operator
