# Xrootd operator OLM Integration workflow
---
name: "Xrootd operator OLM"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  bundle:
    name: Bundle Operator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Operator SDK
        uses: shivanshs9/setup-k8s-operator-sdk@v1
        with:
          version: "^0.18.0"
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install operator-courier
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip3 install operator-courier==2.1.9
      - name: Bundle the operator
        run: make bundle
      - name: Lint Bundle
        run: make lint-bundle
